/* tslint:disable */
/* eslint-disable */
/**
 * anzeigen_portal API
 * anzeigen_portal API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface SwbImageSanitize
 */
export interface SwbImageSanitize {
    /**
     * 
     * @type {string}
     * @memberof SwbImageSanitize
     */
    imageBase64?: string;
}

/**
 * Check if a given object implements the SwbImageSanitize interface.
 */
export function instanceOfSwbImageSanitize(value: object): value is SwbImageSanitize {
    return true;
}

export function SwbImageSanitizeFromJSON(json: any): SwbImageSanitize {
    return SwbImageSanitizeFromJSONTyped(json, false);
}

export function SwbImageSanitizeFromJSONTyped(json: any, ignoreDiscriminator: boolean): SwbImageSanitize {
    if (json == null) {
        return json;
    }
    return {
        
        'imageBase64': json['imageBase64'] == null ? undefined : json['imageBase64'],
    };
}

  export function SwbImageSanitizeToJSON(json: any): SwbImageSanitize {
      return SwbImageSanitizeToJSONTyped(json, false);
  }

  export function SwbImageSanitizeToJSONTyped(value?: SwbImageSanitize | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'imageBase64': value['imageBase64'],
    };
}

