/* eslint-disable */
/**
 * anzeigen_portal API
 * anzeigen_portal API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface SwbUserFind
 */
export interface SwbUserFind {
    /**
     * 
     * @type {string}
     * @memberof SwbUserFind
     */
    lhmObjectID?: string;
}

/**
 * Check if a given object implements the SwbUserFind interface.
 */
export function instanceOfSwbUserFind(value: object): value is SwbUserFind {
    return true;
}

export function SwbUserFindFromJSON(json: any): SwbUserFind {
    return SwbUserFindFromJSONTyped(json, false);
}

export function SwbUserFindFromJSONTyped(json: any, ignoreDiscriminator: boolean): SwbUserFind {
    if (json == null) {
        return json;
    }
    return {
        
        'lhmObjectID': json['lhmObjectID'] == null ? undefined : json['lhmObjectID'],
    };
}

  export function SwbUserFindToJSON(json: any): SwbUserFind {
      return SwbUserFindToJSONTyped(json, false);
  }

  export function SwbUserFindToJSONTyped(value?: SwbUserFind | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'lhmObjectID': value['lhmObjectID'],
    };
}

