/* tslint:disable */
/* eslint-disable */
/**
 * anzeigen_portal API
 * anzeigen_portal API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface SwbUserTO
 */
export interface SwbUserTO {
    /**
     * 
     * @type {number}
     * @memberof SwbUserTO
     */
    id?: number;
    /**
     * 
     * @type {string}
     * @memberof SwbUserTO
     */
    lhmObjectId?: string;
    /**
     * 
     * @type {string}
     * @memberof SwbUserTO
     */
    displayName?: string;
    /**
     * 
     * @type {string}
     * @memberof SwbUserTO
     */
    email?: string;
}

/**
 * Check if a given object implements the SwbUserTO interface.
 */
export function instanceOfSwbUserTO(value: object): value is SwbUserTO {
    return true;
}

export function SwbUserTOFromJSON(json: any): SwbUserTO {
    return SwbUserTOFromJSONTyped(json, false);
}

export function SwbUserTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): SwbUserTO {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'lhmObjectId': json['lhmObjectId'] == null ? undefined : json['lhmObjectId'],
        'displayName': json['displayName'] == null ? undefined : json['displayName'],
        'email': json['email'] == null ? undefined : json['email'],
    };
}

  export function SwbUserTOToJSON(json: any): SwbUserTO {
      return SwbUserTOToJSONTyped(json, false);
  }

  export function SwbUserTOToJSONTyped(value?: SwbUserTO | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'lhmObjectId': value['lhmObjectId'],
        'displayName': value['displayName'],
        'email': value['email'],
    };
}

