--
-- PostgreSQL database dump
--

-- Dumped from database version 16.4
-- Dumped by pg_dump version 16.4

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- TOC entry 216 (class 1259 OID 102954)
-- Name: t_ad; Type: TABLE; Schema: public; Owner: admin
--

CREATE TABLE public.t_ad (
    active boolean NOT NULL,
    condition smallint,
    expiry_date date NOT NULL,
    price double precision,
    rental_date date,
    views integer NOT NULL,
    creation_date_time timestamp(6) without time zone NOT NULL,
    fk_ad_category_id bigint NOT NULL,
    fk_ad_id bigint,
    fk_swb_user_id bigint NOT NULL,
    id bigint NOT NULL,
    title character varying(120) NOT NULL,
    link character varying(512),
    description character varying(2000) NOT NULL,
    ad_type character varying(255) NOT NULL,
    email character varying(255),
    phone character varying(255),
    image_preview oid,
    CONSTRAINT t_ad_ad_type_check CHECK (((ad_type)::text = ANY ((ARRAY['SEEK'::character varying, 'OFFER'::character varying, 'RENTAL'::character varying])::text[]))),
    CONSTRAINT t_ad_condition_check CHECK (((condition >= 0) AND (condition <= 4)))
);


ALTER TABLE public.t_ad OWNER TO admin;

--
-- TOC entry 218 (class 1259 OID 102966)
-- Name: t_ad_category; Type: TABLE; Schema: public; Owner: admin
--

CREATE TABLE public.t_ad_category (
    standard boolean NOT NULL,
    id bigint NOT NULL,
    name character varying(255) NOT NULL
);


ALTER TABLE public.t_ad_category OWNER TO admin;

--
-- TOC entry 217 (class 1259 OID 102965)
-- Name: t_ad_category_id_seq; Type: SEQUENCE; Schema: public; Owner: admin
--

ALTER TABLE public.t_ad_category ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.t_ad_category_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 215 (class 1259 OID 102953)
-- Name: t_ad_id_seq; Type: SEQUENCE; Schema: public; Owner: admin
--

ALTER TABLE public.t_ad ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.t_ad_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 220 (class 1259 OID 102972)
-- Name: t_setting; Type: TABLE; Schema: public; Owner: admin
--

CREATE TABLE public.t_setting (
    flag_value boolean,
    number_value integer,
    fk_ad_id bigint,
    id bigint NOT NULL,
    setting_name character varying(255) NOT NULL,
    text_value character varying(255),
    CONSTRAINT t_setting_setting_name_check CHECK (((setting_name)::text = ANY ((ARRAY['MOTD'::character varying, 'MAX_SWB_IMAGE_SIZE'::character varying, 'MAX_SWB_FILE_SIZE'::character varying, 'MAX_SWB_FILES_LENGTH'::character varying, 'MAX_EXPIRY_DATE_RANGE'::character varying, 'AGB_FILE'::character varying, 'DATENSCHUTZHINWEISE_FILE'::character varying, 'MAX_PAGE_SIZE'::character varying, 'DEFAULT_SORTING'::character varying, 'DEFAULT_ORDERING'::character varying, 'MAX_ARCHIVE_DATE_RANGE'::character varying, 'MAX_RENTAL_DATE_RANGE'::character varying])::text[])))
);


ALTER TABLE public.t_setting OWNER TO admin;

--
-- TOC entry 219 (class 1259 OID 102971)
-- Name: t_setting_id_seq; Type: SEQUENCE; Schema: public; Owner: admin
--

ALTER TABLE public.t_setting ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.t_setting_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 222 (class 1259 OID 102985)
-- Name: t_swb_file; Type: TABLE; Schema: public; Owner: admin
--

CREATE TABLE public.t_swb_file (
    size integer NOT NULL,
    fk_ad_id bigint,
    id bigint NOT NULL,
    name character varying(255) NOT NULL,
    file oid NOT NULL
);


ALTER TABLE public.t_swb_file OWNER TO admin;

--
-- TOC entry 221 (class 1259 OID 102984)
-- Name: t_swb_file_id_seq; Type: SEQUENCE; Schema: public; Owner: admin
--

ALTER TABLE public.t_swb_file ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.t_swb_file_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 224 (class 1259 OID 102991)
-- Name: t_swb_image; Type: TABLE; Schema: public; Owner: admin
--

CREATE TABLE public.t_swb_image (
    id bigint NOT NULL,
    image oid NOT NULL
);


ALTER TABLE public.t_swb_image OWNER TO admin;

--
-- TOC entry 223 (class 1259 OID 102990)
-- Name: t_swb_image_id_seq; Type: SEQUENCE; Schema: public; Owner: admin
--

ALTER TABLE public.t_swb_image ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.t_swb_image_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 226 (class 1259 OID 102997)
-- Name: t_swb_user; Type: TABLE; Schema: public; Owner: admin
--

CREATE TABLE public.t_swb_user (
    id bigint NOT NULL,
    display_name character varying(255) NOT NULL,
    lhm_object_id character varying(255) NOT NULL
);


ALTER TABLE public.t_swb_user OWNER TO admin;

--
-- TOC entry 225 (class 1259 OID 102996)
-- Name: t_swb_user_id_seq; Type: SEQUENCE; Schema: public; Owner: admin
--

ALTER TABLE public.t_swb_user ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.t_swb_user_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 227 (class 1259 OID 103006)
-- Name: theentity; Type: TABLE; Schema: public; Owner: admin
--

CREATE TABLE public.theentity (
    textattribute character varying(8) NOT NULL,
    id uuid NOT NULL
);


ALTER TABLE public.theentity OWNER TO admin;

--
-- TOC entry 3306 (class 2606 OID 103044)
-- Name: flyway_schema_history flyway_schema_history_pk; Type: CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public.flyway_schema_history
    ADD CONSTRAINT flyway_schema_history_pk PRIMARY KEY (installed_rank);


--
-- TOC entry 3288 (class 2606 OID 102970)
-- Name: t_ad_category t_ad_category_pkey; Type: CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public.t_ad_category
    ADD CONSTRAINT t_ad_category_pkey PRIMARY KEY (id);


--
-- TOC entry 3284 (class 2606 OID 102964)
-- Name: t_ad t_ad_fk_ad_id_key; Type: CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public.t_ad
    ADD CONSTRAINT t_ad_fk_ad_id_key UNIQUE (fk_ad_id);


--
-- TOC entry 3286 (class 2606 OID 102962)
-- Name: t_ad t_ad_pkey; Type: CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public.t_ad
    ADD CONSTRAINT t_ad_pkey PRIMARY KEY (id);


--
-- TOC entry 3290 (class 2606 OID 102981)
-- Name: t_setting t_setting_fk_ad_id_key; Type: CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public.t_setting
    ADD CONSTRAINT t_setting_fk_ad_id_key UNIQUE (fk_ad_id);


--
-- TOC entry 3292 (class 2606 OID 102979)
-- Name: t_setting t_setting_pkey; Type: CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public.t_setting
    ADD CONSTRAINT t_setting_pkey PRIMARY KEY (id);


--
-- TOC entry 3294 (class 2606 OID 102983)
-- Name: t_setting t_setting_setting_name_key; Type: CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public.t_setting
    ADD CONSTRAINT t_setting_setting_name_key UNIQUE (setting_name);


--
-- TOC entry 3296 (class 2606 OID 102989)
-- Name: t_swb_file t_swb_file_pkey; Type: CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public.t_swb_file
    ADD CONSTRAINT t_swb_file_pkey PRIMARY KEY (id);


--
-- TOC entry 3298 (class 2606 OID 102995)
-- Name: t_swb_image t_swb_image_pkey; Type: CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public.t_swb_image
    ADD CONSTRAINT t_swb_image_pkey PRIMARY KEY (id);


--
-- TOC entry 3300 (class 2606 OID 103005)
-- Name: t_swb_user t_swb_user_lhm_object_id_key; Type: CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public.t_swb_user
    ADD CONSTRAINT t_swb_user_lhm_object_id_key UNIQUE (lhm_object_id);


--
-- TOC entry 3302 (class 2606 OID 103003)
-- Name: t_swb_user t_swb_user_pkey; Type: CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public.t_swb_user
    ADD CONSTRAINT t_swb_user_pkey PRIMARY KEY (id);


--
-- TOC entry 3304 (class 2606 OID 103010)
-- Name: theentity theentity_pkey; Type: CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public.theentity
    ADD CONSTRAINT theentity_pkey PRIMARY KEY (id);


--
-- TOC entry 3307 (class 1259 OID 103045)
-- Name: flyway_schema_history_s_idx; Type: INDEX; Schema: public; Owner: admin
--

CREATE INDEX flyway_schema_history_s_idx ON public.flyway_schema_history USING btree (success);


--
-- TOC entry 3308 (class 2606 OID 103011)
-- Name: t_ad fk3fiu3b6t0056frvqrii5susm3; Type: FK CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public.t_ad
    ADD CONSTRAINT fk3fiu3b6t0056frvqrii5susm3 FOREIGN KEY (fk_ad_category_id) REFERENCES public.t_ad_category(id);


--
-- TOC entry 3309 (class 2606 OID 103016)
-- Name: t_ad fk44hbbg55n8vwt0n9ym4dyojg6; Type: FK CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public.t_ad
    ADD CONSTRAINT fk44hbbg55n8vwt0n9ym4dyojg6 FOREIGN KEY (fk_ad_id) REFERENCES public.t_swb_image(id);


--
-- TOC entry 3311 (class 2606 OID 103026)
-- Name: t_setting fkbyft3va0rdl9b7xswrbof4nld; Type: FK CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public.t_setting
    ADD CONSTRAINT fkbyft3va0rdl9b7xswrbof4nld FOREIGN KEY (fk_ad_id) REFERENCES public.t_swb_file(id);


--
-- TOC entry 3310 (class 2606 OID 103021)
-- Name: t_ad fkifvylntlsar7dt9hbhhf0ed6; Type: FK CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public.t_ad
    ADD CONSTRAINT fkifvylntlsar7dt9hbhhf0ed6 FOREIGN KEY (fk_swb_user_id) REFERENCES public.t_swb_user(id);


--
-- TOC entry 3312 (class 2606 OID 103031)
-- Name: t_swb_file fkmgeq2nil9p69lv4xsa3nbqibo; Type: FK CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public.t_swb_file
    ADD CONSTRAINT fkmgeq2nil9p69lv4xsa3nbqibo FOREIGN KEY (fk_ad_id) REFERENCES public.t_ad(id);


--
-- TOC entry 3461 (class 0 OID 0)
-- Dependencies: 5
-- Name: SCHEMA public; Type: ACL; Schema: -; Owner: pg_database_owner
--

REVOKE USAGE ON SCHEMA public FROM PUBLIC;


-- Completed on 2025-04-22 12:51:42 UTC

--
-- PostgreSQL database dump complete
--

