name: release-maven-image

on:
  workflow_dispatch:
    inputs:
      releaseVersion:
        description: "Default version to use when preparing a release."
        required: true
        default: "X.Y.Z"
      developmentVersion:
        description: "Default version to use for new local working copy."
        required: true
        default: "X.Y.Z-SNAPSHOT"
      app-path:
        type: choice
        description: Service-Name
        required: true
        options:
          - anzeigen-backend # todo: muss angepasst werden. eigenen Ordner verwenden
          - anzeigen-frontend # todo: muss angepasst werden. eigenen Ordner verwenden

jobs:
  release-maven:
    runs-on: ubuntu-latest
    outputs:
      MVN_ARTIFACT_ID: ${{ steps.maven-release-step.outputs.MVN_ARTIFACT_ID }}
    env:
      TZ: Europe/Berlin # timezone
    steps:
      - id: maven-release-step
        uses: it-at-m/lhm_actions/action-templates/actions/action-maven-release@175e2b8e7162b91368e37f1ea5b74bf5ec3ee10a # v1.0.4
        with:
          app-path: "/${{ github.event.inputs.app-path }}"
          releaseVersion: "${{ github.event.inputs.releaseVersion }}"
          developmentVersion: "${{ github.event.inputs.developmentVersion }}"

  build-image:
    runs-on: ubuntu-latest
    needs: release-maven
    steps:
      - uses: it-at-m/lhm_actions/action-templates/actions/action-build-image@175e2b8e7162b91368e37f1ea5b74bf5ec3ee10a # v1.0.4
        with:
          path: "${{ github.event.inputs.app-path }}"
          name: "${{ github.event.inputs.app-path }}"
          registry-password: ${{ secrets.GITHUB_TOKEN }}
          registry: ghcr.io
          registry-username: ${{ github.actor }}
          image-tags: |
            type=semver,pattern={{version}},value=${{ github.event.inputs.releaseVersion }}

  create-github-release:
    needs: release-maven
    runs-on: ubuntu-latest
    steps:
      - name: Create GitHub Release
        id: create_release
        uses: softprops/action-gh-release@c95fe1489396fe8a9eb87c0abf8aa5b2ef267fda # v2.2.1
        with:
          tag_name: ${{needs.release-maven.outputs.MVN_ARTIFACT_ID}}-${{ github.event.inputs.releaseVersion }}
          draft: false
          prerelease: false
          generate_release_notes: false
